# Generated by Django 3.2.12 on 2022-04-15 22:19

from django.db import migrations, models
from ckeditor.fields import RichTextField

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', RichTextField()),
                ('creation_date', models.DateTimeField(blank=True)),
                ('modification_date', models.DateTimeField(blank=True)),
                ('erase_date', models.DateTimeField(blank=True)),
                ('active', models.BooleanField(blank=True)),
            ],
        ),
    ]
