# Generated by Django 3.2.13 on 2022-04-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220422_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
