# Generated by Django 3.2.13 on 2022-04-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='active',
        ),
    ]
