# Generated by Django 3.2.13 on 2022-04-23 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_page_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='erase_date',
        ),
        migrations.AlterField(
            model_name='page',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='page',
            name='modification_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
