# Generated by Django 3.2.13 on 2022-04-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_page_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
    ]
