# Generated by Django 3.2.13 on 2022-04-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220422_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
