# Generated by Django 3.2.13 on 2022-04-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/entrega_final_carrizo/media/default.png', null=True, upload_to='profile_images'),
        ),
    ]
